import { PAL } from '../palette.js';

// Cada piso es una región subterránea completa. El bioma define geografía, flora, aldeas,
// monumento, clima, música y fauna. Solo se usan colores de la paleta maestra.
export const BIOMES = {
  bosque: {
    name: 'Bosque de Raíces',
    music: 'bosque',
    ground: { style: 'grass', colors: [PAL.moss0, PAL.moss1, PAL.moss2] },
    path: [PAL.rust0, PAL.rust1, PAL.rust2],
    water: [PAL.steel0, PAL.steel1, PAL.steel2],
    rock: { top: [PAL.ink, PAL.night, PAL.moss0, PAL.moss1], face: [PAL.night, PAL.stone0, PAL.stone1, PAL.moss1], style: 'rock' },
    tallGrass: [PAL.moss0, PAL.moss1, PAL.moss2],
    leaves: [PAL.night, PAL.moss0, PAL.moss1, PAL.moss2],
    geo: { water: 0.34, rock: 0.68, forest: 0.46, treeDensity: 0.55, grass: 0.52, river: 0.8 },
    trees: ['arbol', 'pino', 'arbol'],
    rareTree: ['hongo', 0.06],
    decor: [['arbusto', 0.02], ['roca', 0.006], ['juncos', 0.03, 'orilla'], ['tocon', 0.004], ['helecho', 0.025], ['flores', 0.012], ['tronco', 0.003], ['estalagmita', 0.05, 'roca'], ['cristal', 0.006, 'roca']],
    decals: ['raices', 'flores', 'musgo'],
    house: 'madera',
    landmark: 'arbol_ancestral',
    particles: { kind: 'esporas', colors: [PAL.ember2, PAL.moss2, PAL.bone1] },
    battle: { bands: [PAL.ink, PAL.night, PAL.moss0, PAL.moss1], silhouette: 'arboles', floor: PAL.moss0 },
    archetypes: { beast: 3, crawler: 3, wraith: 1, humanoid: 1 },
    ramps: ['rot', 'bone', 'flesh'],
    villages: ['Aldea del Musgo', 'Caserío de Leñadores', 'Refugio de las Raíces', 'Hondonada Verde'],
    forestNames: ['Espesura de los Susurros', 'Bosque sin Cielo', 'Arboleda Ahorcada'],
    lakeNames: ['Lago del Espejo Negro', 'Charca de las Luciérnagas'],
  },
  necropolis: {
    name: 'Necrópolis',
    music: 'catacumbas',
    ground: { style: 'ash', colors: [PAL.stone0, PAL.stone1, PAL.stone2] },
    path: [PAL.stone1, PAL.stone2, PAL.stone3],
    water: [PAL.ink, PAL.night, PAL.dusk],
    rock: { top: [PAL.ink, PAL.night, PAL.shade, PAL.dusk], face: [PAL.shade, PAL.stone0, PAL.stone1, PAL.stone2], style: 'brick' },
    tallGrass: [PAL.stone0, PAL.bone0, PAL.bone1],
    leaves: [PAL.ink, PAL.shade, PAL.dusk, PAL.stone1],
    geo: { water: 0.3, rock: 0.68, forest: 0.6, treeDensity: 0.3, grass: 0.6, river: 0.2 },
    trees: ['seco', 'seco', 'arbol'],
    decor: [['lapida', 0.03], ['cruz', 0.012], ['vela', 0.012], ['roca', 0.004], ['estalagmita', 0.06, 'roca'], ['cristal', 0.005, 'roca']],
    decals: ['huesos', 'grietas', 'huesos'],
    house: 'mausoleo',
    landmark: 'coloso',
    particles: { kind: 'ceniza', colors: [PAL.bone0, PAL.stone3, PAL.bone1] },
    battle: { bands: [PAL.ink, PAL.night, PAL.shade, PAL.dusk], silhouette: 'lapidas', floor: PAL.stone0 },
    archetypes: { humanoid: 3, wraith: 3, beast: 1, crawler: 1 },
    ramps: ['bone', 'flesh', 'void'],
    villages: ['Villa Sepulcro', 'Caserío de las Velas', 'Refugio del Sepulturero'],
    forestNames: ['Arboleda de los Colgados', 'Campo de Tumbas'],
    lakeNames: ['Aguas Negras', 'Estanque de los Ahogados'],
  },
  pantano: {
    name: 'Pantano Hundido',
    music: 'caverna',
    ground: { style: 'mud', colors: [PAL.rust0, PAL.moss0, PAL.moss1] },
    path: [PAL.rust0, PAL.rust1, PAL.rust2],
    water: [PAL.moss0, PAL.steel0, PAL.steel1],
    rock: { top: [PAL.ink, PAL.night, PAL.moss0, PAL.rust0], face: [PAL.night, PAL.rust0, PAL.moss0, PAL.moss1], style: 'rock' },
    tallGrass: [PAL.moss0, PAL.moss1, PAL.moss2],
    leaves: [PAL.night, PAL.moss0, PAL.moss1, PAL.bone0],
    geo: { water: 0.44, rock: 0.72, forest: 0.5, treeDensity: 0.4, grass: 0.45, river: 1 },
    trees: ['sauce', 'seco', 'sauce'],
    rareTree: ['hongo', 0.04],
    decor: [['juncos', 0.08, 'orilla'], ['tocon', 0.01], ['roca', 0.004], ['hongo_chico', 0.01], ['helecho', 0.02], ['tronco', 0.005], ['estalagmita', 0.04, 'roca'], ['cristal', 0.006, 'roca']],
    decals: ['musgo', 'raices', 'musgo'],
    house: 'palafito',
    landmark: 'arbol_ancestral',
    particles: { kind: 'niebla', colors: [PAL.stone2, PAL.stone3, PAL.bone0] },
    battle: { bands: [PAL.ink, PAL.moss0, PAL.moss1, PAL.stone1], silhouette: 'juncos', floor: PAL.moss0 },
    archetypes: { crawler: 3, beast: 2, wraith: 2 },
    ramps: ['rot', 'void', 'bone'],
    villages: ['Aldea de los Ahogados', 'Palafitos de Grisalma', 'Refugio del Barquero'],
    forestNames: ['Manglar Podrido', 'Bosque de Sauces Llorones'],
    lakeNames: ['Ciénaga Muda', 'Lodazal de las Voces'],
  },
  ciudad: {
    name: 'Ciudad en Ruinas',
    music: 'ruinas',
    ground: { style: 'ash', colors: [PAL.steel0, PAL.stone0, PAL.stone1] },
    path: [PAL.stone1, PAL.stone2, PAL.stone3],
    water: [PAL.night, PAL.steel0, PAL.steel1],
    rock: { top: [PAL.ink, PAL.night, PAL.steel0, PAL.steel1], face: [PAL.night, PAL.steel0, PAL.steel1, PAL.steel2], style: 'brick' },
    tallGrass: [PAL.moss0, PAL.moss1, PAL.stone2],
    leaves: [PAL.night, PAL.moss0, PAL.moss1, PAL.stone2],
    geo: { water: 0.28, rock: 0.7, forest: 0.64, treeDensity: 0.25, grass: 0.58, river: 0.3 },
    trees: ['seco', 'arbol'],
    decor: [['columna', 0.02], ['escombro', 0.03], ['estatua', 0.004], ['farol_roto', 0.006], ['flores', 0.004], ['estalagmita', 0.04, 'roca']],
    decals: ['escombros', 'grietas', 'sangre'],
    house: 'ruina',
    landmark: 'coloso',
    particles: { kind: 'polvo', colors: [PAL.stone3, PAL.bone0, PAL.stone2] },
    battle: { bands: [PAL.ink, PAL.night, PAL.steel0, PAL.steel1], silhouette: 'columnas', floor: PAL.steel0 },
    archetypes: { humanoid: 4, wraith: 2, beast: 1 },
    ramps: ['steel', 'rust', 'flesh'],
    villages: ['Barrio del Último Farol', 'Plaza de los Mendigos', 'Refugio de la Muralla'],
    forestNames: ['Jardines Muertos', 'Avenida de las Estatuas'],
    lakeNames: ['Fuente Inundada', 'Cisterna Abierta'],
  },
  ceniza: {
    name: 'Páramo de Ceniza',
    music: 'eco',
    ground: { style: 'ash', colors: [PAL.shade, PAL.dusk, PAL.stone0] },
    path: [PAL.stone0, PAL.stone1, PAL.stone2],
    water: [PAL.blood1, PAL.ember0, PAL.ember1],
    rock: { top: [PAL.ink, PAL.night, PAL.shade, PAL.blood0], face: [PAL.night, PAL.shade, PAL.dusk, PAL.blood0], style: 'rock' },
    tallGrass: [PAL.shade, PAL.rust0, PAL.rust1],
    leaves: [PAL.ink, PAL.shade, PAL.dusk, PAL.stone1],
    geo: { water: 0.3, rock: 0.66, forest: 0.62, treeDensity: 0.22, grass: 0.66, river: 0.6 },
    trees: ['seco'],
    decor: [['roca', 0.02], ['pena', 0.006], ['hueso_grande', 0.006], ['estalagmita', 0.07, 'roca'], ['cristal', 0.008, 'roca']],
    decals: ['grietas', 'huesos', 'sangre'],
    house: 'ruina',
    landmark: 'costillar',
    particles: { kind: 'brasas', colors: [PAL.ember1, PAL.blood3, PAL.ember2] },
    battle: { bands: [PAL.ink, PAL.blood0, PAL.shade, PAL.dusk], silhouette: 'costillas', floor: PAL.shade },
    archetypes: { wraith: 3, beast: 3, humanoid: 1 },
    ramps: ['rust', 'void', 'flesh'],
    villages: ['Campamento de Hollín', 'Refugio de Ceniza', 'Asentamiento del Eclipse'],
    forestNames: ['Bosque Calcinado', 'Llanura de los Huesos'],
    lakeNames: ['Río de Brasas', 'Lago de Magma'],
    lavaWater: true,
  },
  // Solo aparece como fragmento multiversal inyectado en otras regiones.
  abismo: {
    name: 'Eco de otra realidad',
    music: 'eco',
    ground: { style: 'mud', colors: [PAL.blood0, PAL.rust0, PAL.rust1] },
    path: [PAL.blood0, PAL.blood1, PAL.blood2],
    water: [PAL.ink, PAL.blood0, PAL.blood1],
    rock: { top: [PAL.ink, PAL.blood0, PAL.rust0, PAL.blood1], face: [PAL.blood0, PAL.rust0, PAL.blood1, PAL.ember0], style: 'rock' },
    tallGrass: [PAL.blood0, PAL.blood1, PAL.blood2],
    leaves: [PAL.ink, PAL.blood0, PAL.blood1, PAL.blood2],
    battle: { bands: [PAL.ink, PAL.blood0, PAL.rust0, PAL.blood1], silhouette: 'costillas', floor: PAL.blood0 },
    archetypes: { wraith: 2, humanoid: 1, beast: 1 },
    ramps: ['rust', 'void'],
  },
};

export const REGION_BIOMES = ['bosque', 'necropolis', 'pantano', 'ciudad', 'ceniza'];

export function pickBiome(rng, depth) {
  if (depth === 1) return 'bosque';
  return rng.pick(REGION_BIOMES);
}
